### ISSUE TITLE
CI cluster has flaky admin cluster role

### ISSUE THREAD

**Issue by dmage** [openshift/test-infra#164]
Found in https://github.com/openshift/image-registry/pull/117.

Our integration tests flake because of clusterroles.rbac.authorization.k8s.io "admin".

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_image-registry/117/pull-ci-image-registry-integration/72/ (successful build)

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_image-registry/117/pull-ci-image-registry-integration/73/
> cluster roles did not aggregate: clusterroles.rbac.authorization.k8s.io "admin" not found

Why does it sometimes disappear?

cc @openshift/sig-security (is it sig-auth?)

**Comment by enj** [comment]
The logic at:

https://github.com/openshift/image-registry/blob/d46780e26be71f654f8bde981cf7570e0dc31877/pkg/testframework/master.go#L320-L355

is incorrect.  It should ignore `NotFound` errors inside of the `wait.Poll`.  Otherwise you will race with the initial creation of those objects.  Looks like it was copied from:

https://github.com/openshift/origin/blob/b7daec7e4e2a745480b83dfe56bb4e10429a3387/test/util/server/server.go#L493-L526

which is also incorrect in the same way.

In general the wait logic is not very robust because it takes a while for all of the cluster roles to stabilize (the nuance of which is not captured by a simple length check).
